version: '3'
services:
  space-engineers-docker-bootstrapper:
    # image: mmmaxwwwell/space-engineers-docker-bootstrapper
    build:
      context: .
      dockerfile: Dockerfile
    container_name: space-engineers-docker-bootstrapper
    restart: always
    volumes:
      - ./appdata/space-engineers/World:/appdata/space-engineers/World
      - ./appdata/space-engineers/SpaceEngineers-Dedicated.cfg:/appdata/space-engineers/SpaceEngineersDedicated/SpaceEngineers-Dedicated.cfg
      - ./appdata/space-engineers-docker-bootstrapper/storage:/home/node/app/storage
    env_file:
      - ./secrets/space-engineers-docker-bootstrapper.env
    networks:
      - healthcheck
  se-server:
    image: mmmaxwwwell/space-engineers-dedicated-docker-linux:healthcheck
    container_name: space-engineers-dedicated-docker-linux
    restart: always
    volumes:
      - ./appdata/space-engineers/World:/appdata/space-engineers/World
      - ./appdata/space-engineers/SpaceEngineersDedicated:/appdata/space-engineers/SpaceEngineersDedicated
      - ./appdata/space-engineers/steamcmd:/root/.steam
      - ./appdata/space-engineers/SpaceEngineers-Dedicated.cfg:/appdata/space-engineers/SpaceEngineersDedicated/SpaceEngineers-Dedicated.cfg
    ports:
     - "27016:27016/udp"
    command: sh -c '/wait-for-it.sh space-engineers-docker-bootstrapper:3000 -s -t 300 -- bash /entrypoint.bash'
    networks:
      - healthcheck
  backup-manager:
    image: mmmaxwwwell/backup-manager
    container_name: backup-manager
    restart: always
    volumes:
      - ./appdata/backup_manager/local_backup:/home/node/app/local_backup
      - ./appdata/backup_manager/backup_source:/home/node/app/backup_source
      - ./appdata/backup_manager/storage:/home/node/app/storage
    env_file:
      - ./secrets/backup_manager.env
    networks:
      - healthcheck
networks:
  healthcheck:
    external: false
